# This is a basic workflow to help you get started with Actions

name: Windows Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Setting up Premake
      - uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"

        # Generate project
      - name: Generate project files
        run: |
              cd Scripts
              GenVisualStudio2022.bat

      # Setting up msbuild
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

        # Build project
      - name: Build app for release
        run: msbuild Source\MacroTodo.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
